#!/bin/bash
_name="main"
_elf=""
_ld=""
if [ "$( uname -m )" == "x86_64" ] ; then
	_elf="elf64 -dM86x64"
	_ld="elf_x86_64"
else
	_elf="elf32 -dMi386"
	_ld="elf_"
fif

nasm -f ${elf} -l main.lst main.asm

if [ -f "main.o" ] ; then
	gcc -o test main.o
fi
